POST https://webexapis.com/v1/messages
Content-Type: application/json
Authorization: Bearer ZjU1ZGU0ZmEtZDU5Ny00NjJjLTk2ZWMtYmQ4MGM0NjhiZmQ3NjQ3YzM4NDMtMTdm_P0A1_023934c2-3934-48f9-b7e3-18314460f059

{
    "roomId":"Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vMTc3YzZhYzAtOTk5NS0xMWVkLWIwNWItMjllOTFmZjM2YWQ0",
    "text":"Mensaje",
    "markdown":"Hola desde visual studio Firma: Jose :v"
}

###
DELETE  https://webexapis.com/v1/messages/Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL01FU1NBR0UvMTU4Mjg4ZDAtOTk5MC0xMWVkLWIwMjUtZDFiMTk4YjJlOWY1
Content-Type: application/json
Authorization: Bearer OTliNTc3OTYtNTczZC00MDI5LTlmMDAtOTQ1YjRhYTgwNmEyODBkZWM0YWUtOTQ3_P0A1_ff79c397-9d79-44f7-8296-8858b58f5ba8

